# Auto-generated by /mnt/workspace/edk2-msm/Common/edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/mnt/workspace/edk2-msm/workspace
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/mnt/workspace/edk2-msm/Common/edk2/BaseTools
fi
if [ -e /mnt/workspace/edk2-msm/Common/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//mnt/workspace/edk2-msm/Common/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/mnt/workspace/edk2-msm/Common/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
